apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - rbac.yaml
  - storageclass.yaml

commonLabels:
  app: wd-provisioner

replicas:
  - name: wd-provisioner-controller
    count: 1
