apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml
  - rbac.yaml
  - storageclass.yaml

labels:
  - pairs:
      app: wd-provisioner
    includeSelectors: true

secretGenerator:
  - name: wd-iscsi
    files:
      - ssh-privatekey=id_rsa
    type: kubernetes.io/ssh-auth
    options:
      disableNameSuffixHash: true
