apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-wd-provisioner
subjects:
  - kind: User
    name: system:bootstrap:abcdef
roleRef:
  # FIXME
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
