apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test

resources:
  - ../../kustomize/
  - namespace.yaml
  - test-rbac.yaml

replicas:
  - name: wd-provisioner-controller
    count: 0

secretGenerator:
  - name: wd-iscsi
    behavior: merge
    files:
      - ssh-privatekey=id_rsa
    type: kubernetes.io/ssh-auth

patches:
  - path: storageclass_patch.yaml
  - patch: |-
      - op: replace
        path: /rules/0/verbs # NOTE: persistentvolumeclaims
        value: ["*"]
    target:
      kind: ClusterRole
      name: wd-provisioner
