apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test

resources:
  - ../../kustomize/
  - namespace.yaml
  - test-rbac.yaml

patches:
  - patch: |-
      - op: add
        path: /rules/0/verbs/- # NOTE: persistentvolumeclaims
        value: create
      - op: add
        path: /rules/0/verbs/- # NOTE: persistentvolumeclaims
        value: patch
    target:
      kind: ClusterRole
      name: wd-provisioner
